### ISSUE TITLE
Script intermittently gets stuck transitioning from page 1

### ISSUE THREAD

**Issue by shinji257** [Cortys/comixology-backup#26]
Occasionally the script seems to get stuck moving from page 1 (the cover) to page 2.  This may be more of a website issue though.  Basically what happens is that it hits up page 1 then tries to move to page 2 and the screen never updates.  Now then I do have a workaround.

Workaround: Close the tab that is trying to capture the comic then start the scan again.  This time it will either work (if you have prompt to continue off) or ask if you want to start at either page 2 or the beginning (if the prompt is on).  If you get the 2nd tell it to continue from page 2.  The backup script is smart enough to detect it isn't on page 1 and goes back to that and actually works.

Why it works: From the best I can tell page 2 doesn't show at first due to a possible transition.  When you reload the page it starts at page 2 automatically which is now downloaded.  The script then goes back and is able to start at page 1 normally.

This isn't related to #25 though.  I just checked that one and it is indeed as described over there.

**Comment by Cortys** [comment]
Were page transitions enabled when you experienced this problem?

**Comment by shinji257** [comment]
Yes

**Comment by Cortys** [comment]
Ok. Did you try disabling the animation and did you enable "latency compensation" in the extensions options?

**Comment by shinji257** [comment]
At the time I had not.  Later on I did end up turning on latency compensation (your right it is slow) since some larger ones were giving me trouble and stopping at random spots.  There were a few where even my internet connection was at fault ( I think -- switching connections worked ).  As of right now latency compensation is on though.

Keep in mind when I had the issue though before I was on like a 20mbit connection and it was just a couple of randoms that did the weird stuck bit.  I'll probably shut off animations instead of (or in addition to) latency compensation and see if it works out any better.  For now I already finished it all.  I think I only have one giving me issues and that one is related to another bug report that was posted. (forced 2 page (aka manga) mode)

**Comment by Cortys** [comment]
I just added a new latency compensation replacement to the 2.1.0 branch, that should be more robust and customizable without the major slowdowns of the old implementation.

If the new latency handler does not solve your problem, you can set a specific min delay in the options now. Putting in a large enough value should solve any halting and/or blank page problem.

Does this solve your problem?

**Comment by shinji257** [comment]
2.1.0 seems to handle the loading much better now.  It's actually faster in page switching than before even with transitions however I think I'll just leave transitions off now since it doesn't give any weird lag.  I'm testing another bug fix as well and you will see a message there shortly as well.

**Comment by Cortys** [comment]
This bug should be fixed now. Will reopen if someone still experiences problems.
