### ISSUE TITLE
Disabled by Chrome

### ISSUE THREAD

**Issue by infinatalie** [Cortys/comixology-backup#27]
Since Chrome changed their extension rules, you can no longer use extensions that aren't in the Chrome Web Store :( It was nice while it lasted

**Comment by Cortys** [comment]
Which OS are you using?

**Comment by Cortys** [comment]
If you are using Windows, this should solve the problem: https://github.com/Cortys/comixology-backup#second-possibility

**Comment by tomchiverton** [comment]
We could just update the docs to exclude the first possibility ?

**Comment by Cortys** [comment]
The first installation method still is the easiest one and works on Linux and Mac Chrome versions.

Maybe the order of the two could be swapped, but I don't have numbers about OS usage so this might not be appropriate either.

**Comment by Cortys** [comment]
Seems to be inactive and since there is no actual issue here, I'll close this.
