### ISSUE TITLE
Upgraded to 2.1.0 and no longer get past 0%

### ISSUE THREAD

**Issue by phunni** [Cortys/comixology-backup#29]
I've tried performing a new initial scan, but it makes no difference.  I've tried comics that backed up perfectly before and also new ones which I don't yet have a backup for.

I have tried disableing Guided View in the Comixology settings, but it doesn't help.

**Comment by Cortys** [comment]
Can you send me a complete list of your settings in the options page?

**Comment by phunni** [comment]
Sure - here's are screenshots of my settings.  Let me know if you need more.

![Imgur](http://i.imgur.com/BeNjSm1.png)

![Imgur](http://i.imgur.com/Mqv1FdT.png)

The settings for the Comixology reader itself has everything unchecked, although I've also tried with the guided view enabled - with the same results.

**Comment by Cortys** [comment]
Hm. The settings seem to be ok.

* Could you open the options page once again,
* open the JS console (by hitting <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd>),
* type `chrome.storage.local.get(undefined, console.log.bind(console));`
* and give me the result.

It should look something like this:
![screenshot 2015-05-02 13 51 44](https://cloud.githubusercontent.com/assets/1737630/7440968/85b49536-f0d2-11e4-9c71-dd4d562acf8a.png)

**Comment by phunni** [comment]
Here you go:

![Imgur](http://i.imgur.com/QpODsjK.png)

**Comment by phunni** [comment]
Did this provide you with any useful information?

**Comment by phunni** [comment]
More information.  I had been using this in Chromium on Linux and, with previous versions, it had worked perfectly - but then developed this issue.  I have just tried with Chrome Beta and it appears to work, although I haven't yet had the chance to verify the backups.

**Comment by Cortys** [comment]
I was busy the last few days. Your options are looking fine though.

I have a few ideas what might be the problem here but I'll verify that first.

**Comment by Cortys** [comment]
Hm. I tried to reproduce your issue with various Chrome releases and your settings (on OS X though because I didn't want to install a Linux VM).

Backups never actually stalled in my tests. The closest thing to a complete stop at 0% occurred when it throttled my network connection to ~1 Mbit/s, which dramatically delayed the first page render. After about a minute or so the backup started though.

If you still experience the issue, you could try to increase the page swap delay in the options (~1000 ms should be sufficient).

**Comment by sgbeal** [comment]
FWIW, been using 2.1.0 the past couple of days. i've had about 4-5 stalls out of >100 books (all at 40%+), but i don't blame that on the extension - could be caused by any number of transient network problems.

**Comment by Cortys** [comment]
Well, since I cannot reproduce this issue I cannot fix it.

I'll leave this open and look at it again as soon as anyone finds a way to reliably reproduce the problem.

**Comment by tomchiverton** [comment]
2.1.0 is OK for me in Chromium on Ubuntu Linux 14.04 LTS.

**Comment by gargargarrick** [comment]
I have this error with 2.1.0 on Chromium 42, with Mageia Linux RC 5 (32-bit). All comics (irrespective of length or previous functioning status) hang at 0%. My settings are identical to phunni's, posted earlier in the thread. The examination of chrome.storage.local on the options page also yields similar results to theirs, albeit with the addition of "pageSwapDelay: 1000" as per others' suggestions.

Notably, when I turned on error collection and tried to run a scan, I got "Uncaught TypeError: onend is not a function", pointing to line 772 of zip.js (which consists of "onend();") specifically. Does this help in any way?

**Comment by Cortys** [comment]
@gargargarrick Yes this is definitely helpful. The onend error should not cause any halting problems though.

Since all reports came from a Linux system I'll try to reproduce the issue with that next.

**Comment by tomchiverton** [comment]
I have Version 41.0.2272.76 on Ubuntu 14.04 and backups are OK, so it must be something in v42 ?

**Comment by phunni** [comment]
I doubt it makes a difference, but I'm running arch Linux 64 bit. I only mention this because the other person encountering the error said they were running a 32 bit distro. I've also seen this on a few versions of chromium. As I said before, the questions I'm using is to use Chrome beta. Chrome stable may or may not also work.

**Comment by Cortys** [comment]
I just tried to reproduce using Chrome 42 on Ubuntu 14.04 32bit but backups worked as expected.

@gargargarrick Did you disable the "prompt to continue" dialog in the reader options?

**Comment by phunni** [comment]
Remember - this happens on Chromium, not Chrome.

**Comment by sgbeal** [comment]
Using _Chromium_: "Version 41.0.2272.76 Built on Ubuntu 14.04, running on LinuxMint 17 (64-bit)"

2.1.0 has been working fine for me the past week or so.

**Comment by gargargarrick** [comment]
![2015-05-17_workspace 1_001](https://cloud.githubusercontent.com/assets/11541883/7669032/4c4591b0-fc2b-11e4-8694-be9dae7add1f.png)
Yes, "prompt to continue" is disabled.

**Comment by Cortys** [comment]
Is this still an issue?

The reliability of the extension was noticeably improved in 2.3.0. If no one complains, I'll close this issue in a few days.

**Comment by Cortys** [comment]
Closed since this should be fixed.
