### ISSUE TITLE
Is there a way to increase resolution on scans?

### ISSUE THREAD

**Issue by mikemcduffie** [Cortys/comixology-backup#40]
The ComiXology web viewer will allow to set zoom level for higher resolutions than the backup extension captures, but I can find no option to scan at higher resolutions. Is there a way to set this?

**Comment by Cortys** [comment]
No this currently isn't supported. I wasn't aware it was possible to get a higher resolution in the web viewer. Did they add this feature recently?

**Comment by mikemcduffie** [comment]
Not aware of when/if it changed. But I used it yesterday comparing the web resolution to the scan. Definitely larger in web viewer:

Scanned imaged:

![scan](https://cloud.githubusercontent.com/assets/4350221/10118242/d245a858-6428-11e5-8aec-55a17cac4289.jpeg)

Page width zoom in viewer (15 in. laptop):

![page width](https://cloud.githubusercontent.com/assets/4350221/10118247/de10418e-6428-11e5-99f8-f013aaec5cfb.PNG)

Max Zoom with bounce back:

![max zoom withh bounceback](https://cloud.githubusercontent.com/assets/4350221/10118330/1006bc3a-642a-11e5-9378-04e42004c779.PNG)

**Comment by mikemcduffie** [comment]
There's some artifacting (and anti-aliasing?) in the max zoom image but the bounce back makes me want to think that it's constrained to some fixed resolution. The page width image looks clean to my eyes and is larger than the scan/backup image.

**Comment by Cortys** [comment]
When compared pixel by pixel the backuped image looks as sharp as the zoomed image to me. Did you zoom into the backuped image as well?

I'll look into this again next week, since I don't have proper equipment on me right now.

**Comment by mikemcduffie** [comment]
No I didn't do any image analysis, but the page width picture did not look scaled (upsized) to my naked eye. It was very clear. 

I just did a quick and dirty test in an image editor and the page width image may upscaled with a smoothing algorithm. If so, please accept my apologies.

**Comment by Cortys** [comment]
I just did a proper analysis of the web reader content and apparently zooming does not increase the resolution, so I'll close this issue for now.

If you've got a comic that clearly behaves otherwise, please tell me.

**Comment by tomchiverton** [comment]
Please remove the images from the bug :-)
