### ISSUE TITLE
Request Save Button in Settings

### ISSUE THREAD

**Issue by EricPonvelle** [Cortys/comixology-backup#43]
With the settings page, I'd like a "Save Settings" button just to have assurance that the changes I make have been applied.

**Comment by sgbeal** [comment]
The button would be a no-op because once focus leaves any input field (e.g. to the Save button) it's immediately saved. i.e. it would be a false assurance.

**Comment by EricPonvelle** [comment]
I figured, but from a UX perspective, is that really a bad thing? I think it breaks the expectations of the user a bit, though, by nature, this tool is for "higher-end users," so it could be a bit of a needless thing. I just focus on the considerations of a lower experienced audience.

The very least, it'd be pretty simple to implement ;)

**Comment by Cortys** [comment]
I agree that the current behavior might be confusing for less experienced users but adding a no-op button isn't an appropriate solution in my opinion, since it implies that saving manually is necessary.

Maybe a little green checkmark with a label saying `Saved` (or something similar) that appears after each change would do the trick.

What do you think?

**Comment by sgbeal** [comment]
i'd say a useless/noop button is worse than having to get used to auto-save :/. Yes, i also initially looked for a save button, but figured if it was missing then the dev knew what he was doing ;).

i like the idea of some sort of indicator, but i suspect it would always be on/green except when actually typing in a new value.

**Comment by EricPonvelle** [comment]
Even easier may be a Material Design style Snackbar - https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-usage

You make a change, and it says "Changes saved."

**Comment by Cortys** [comment]
@EricPonvelle Great idea! This is something I'll add in the next release. (A pull request would be highly appreciated as well though.)

**Comment by EricPonvelle** [comment]
I'm a bit new to GitHub lingo still. What exactly would I have to do to help that?

**Comment by Cortys** [comment]
Assuming you know HTML, CSS and JavaScript it's quite simple:

1. Fork this repo.
2. Clone your fork to your local machine. If you don't like CLIs, you can use some git client like [GitHub Desktop](http://bit.ly/1NDedID) to do that.
3. Implement the "Save message" feature. `options.html` and `options.js` would need to be changed.
4. Commit and sync the change via the git client. This uploads it to GitHub.
5. [Create a pull request](https://help.github.com/articles/using-pull-requests) = request your modification to be merged into this repo.

**Comment by EricPonvelle** [comment]
I'll give it a try tonight. I'll update when I have it done.

**Comment by EricPonvelle** [comment]
After a lot of research (and help from a friend), I was finally able to implement a toast that'll show when a user selects off of a box.

This is my first real implementation outside of CSS and HTML, so any feedback on that or documentation would be awesome.

**Comment by Cortys** [comment]
Fixed via #45.
