### ISSUE TITLE
Chrome disables the extension

### ISSUE THREAD

**Issue by artorius** [Cortys/comixology-backup#48]
With newer versions of Chrome, this extension gets disabled since it doesn't come from the Chrome store.  Trying to re-enable it does not work.  Any ideas on how to get around this?

**Comment by anorth2** [comment]
The way I've been getting around this is to completely remove and then re-add the extension to chrome.  Alternatively, every time you're done using it, manually disable it and then re-enable when you need it.

**Comment by Cortys** [comment]
Another way to get around this is to [install the extension unpacked](https://github.com/Cortys/comixology-backup#second-possibility).

**Comment by anorth2** [comment]
Chrome still disables it after a while with that method

**Comment by Cortys** [comment]
@anorth2 I've never experienced that. Which OS and Chrome version are you using?

**Comment by anorth2** [comment]
I'm on Chrome 49 and have had that issue ever since first getting this
extension.  Chrome will disable it forcibly after a while whether it's
unpacked or not. (unless I manually disable it, then re-enable as needed)

**Comment by Cortys** [comment]
Which OS do you use? On Windows unpacked extensions are indeed disabled on startup. What you are describing seems to be different though.

**Comment by anorth2** [comment]
Oh I apologize.  I'm on Windows 10.  Unpacked extensions get permanently
disabled after a period of time just like packed extensions.   For now I'm
going to test leaving an unpacked extension enabled and report back once
it's disabled.

**Comment by Cortys** [comment]
Any news on this?

**Comment by anorth2** [comment]
Looks like you were correct before.  It isn't disabling but does give
occasional warnings that it's still enabled.

**Comment by Cortys** [comment]
Ok. Well, in that case there is no way to fix this, other than publishing the extension to the Chrome Web Store where it obviously would be pulled down fairly quickly.

So I think this issue can be closed for now. If I missed a way to make the installation experience more pleasant for Windows users, please let me know and I'll reopen.
