### ISSUE TITLE
Comixology not loading comics when plugin is running

### ISSUE THREAD

**Issue by talkymeat** [Cortys/comixology-backup#50]
Comixology now appears to refuse to open comics (even to read ordinarily) when the backup plugin is running. I've tried to open comics with the plugin disabled, and that has worked; but whenever the plugin is active, Comixology won't load comics.

**Comment by Cortys** [comment]
I could not reproduce this. Which OS and Chrome version are you using?

**Comment by talkymeat** [comment]
Chrome 50.0.2661.86 (64-bit)
OSX El Capitan 10.11.4 (15E65)

I can rule out any interaction with other plugins, as Comixology Backup is the only plugin I have enabled in incognito mode.

**Comment by sgbeal** [comment]
Also can't reproduce:

    Version 49.0.2623.108 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)

i can only assume it has to do with OSX (e.g., did you explicitly ask A&&le for permission?) or with incognito mode (which i don't see a need to use with Comixology).

**Comment by talkymeat** [comment]
A couple of clarifications;

- I get this problem whether I use incognito mode or not; I mentioned it because going incognito is my quickest way of turning all other plugins off.
- I have been a regular Comixology Backup user for a while, and this is the first time this problem has arisen; my last successful use of the plugin (on also OSX) was on 21st April.

**Comment by Cortys** [comment]
That's definitely odd. Still cannot reproduce the issue. The only thing I found is that the extension crashed during the save/download step after a scan when in incognito mode. This, of course, is probably not related to your issue.

Maybe the extension config got broken somehow. You can check it by:
* Opening the options page of the extension,
* open the JS console (by hitting <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd> on Windows, <kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>J</kbd> on Mac),
* type `chrome.storage.local.get(undefined, console.log.bind(console));`
* and give me the result.

**Comment by talkymeat** [comment]
This is what I got, as copied from the console, unaltered except that I put the linebreaks back in. I hope this is what was wanted…
```
chrome.storage.local.get(undefined, console.log.bind(console));
undefined
extensions::SafeBuiltins:19 Object {pagenumAttr: "data-pagenumber", pagenumCorrection: 0, scannedOnce: 1, selectorActiveOnepageButton: "#onepage-btn.active", selectorActivePage: "#thumbnails-list > LI > FIGURE.active"…}
pagenumAttr: "data-pagenumber"
pagenumCorrection: 0
scannedOnce: 1
selectorActiveOnepageButton: "#onepage-btn.active"
selectorActivePage: "#thumbnails-list > LI > FIGURE.active"
selectorBrowseButton: "#browse-btn > IMG"
selectorOnepageButton: "#onepage-btn"
selectorPages: "#thumbnails-list > LI > FIGURE"
selectors: 1
__proto__: Object
__defineGetter__: __defineGetter__()
arguments: null
caller: null
length: 2
name: "__defineGetter__"
__proto__: ()
<function scope>
__defineSetter__: __defineSetter__()
arguments: null
caller: null
length: 2
name: "__defineSetter__"
__proto__: ()
<function scope>
__lookupGetter__: __lookupGetter__()
arguments: null
caller: null
length: 1
name: "__lookupGetter__"
__proto__: ()
<function scope>
__lookupSetter__: __lookupSetter__()
arguments: null
caller: null
length: 1
name: "__lookupSetter__"
__proto__: ()
<function scope>
constructor: Object()
arguments: null
assign: assign()
caller: null
create: create()
defineProperties: defineProperties()
defineProperty: defineProperty()
freeze: freeze()
getOwnPropertyDescriptor: getOwnPropertyDescriptor()
getOwnPropertyNames: getOwnPropertyNames()
getOwnPropertySymbols: getOwnPropertySymbols()
getPrototypeOf: getPrototypeOf()
is: is()
isExtensible: isExtensible()
isFrozen: isFrozen()
isSealed: isSealed()
keys: keys()
length: 1
name: "Object"
preventExtensions: preventExtensions()
prototype: Object
seal: seal()
setPrototypeOf: setPrototypeOf()
__proto__: ()
<function scope>
hasOwnProperty: hasOwnProperty()
arguments: null
caller: null
length: 1
name: "hasOwnProperty"
__proto__: ()
<function scope>
isPrototypeOf: isPrototypeOf()
arguments: null
caller: null
length: 1
name: "isPrototypeOf"
__proto__: ()
<function scope>
propertyIsEnumerable: propertyIsEnumerable()
arguments: null
caller: null
length: 1
name: "propertyIsEnumerable"
__proto__: ()
<function scope>
toLocaleString: toLocaleString()
arguments: null
caller: null
length: 0
name: "toLocaleString"
__proto__: ()
<function scope>
toString: toString()
arguments: null
caller: null
length: 0
name: "toString"
__proto__: ()
<function scope>
valueOf: valueOf()
arguments: null
caller: null
length: 0
name: "valueOf"
__proto__: ()
<function scope>
get __proto__: get __proto__()
arguments: null
caller: null
length: 0
name: "get __proto__"
__proto__: ()
<function scope>
set __proto__: set __proto__()
arguments: null
caller: null
length: 1
name: "set __proto__"
__proto__: ()
<function scope>
```

**Comment by Cortys** [comment]
Thanks! Your config seems to be fine.

Could you try opening the JS console on the cmxlgy "My Books" page as well, reload the page (with the console still open) and see if you get any error logs. If not try clicking on a read or scan button.

Does clicking on "read"/"scan" cause any reaction (reader opens), or just nothing at all?

If it does, please send me the console output for a reader opened via "scan" and the output for one opened via "read".

**Comment by talkymeat** [comment]
So, Google's fun new policy of disabling non Chrome Store extensions forced me to reinstall, and this fixed the problem. :D

**Comment by Cortys** [comment]
Great! Still have no idea what caused the problem in the first place though.
