### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by scooterinab** [Cortys/comixology-backup#53]
I am unable to install the extension using either of the methods provided. Dragging the window installs it, but I am unable to active the extension, Further, closing the browser causes Chrome to deactivate the extension.

Trying the developer method outright fails, generating this error message:
Failed to load extension from: ~PATH (I edited out the path)
Manifest file is missing or unreadable.
Could not load manifest.

**Comment by Cortys** [comment]
Hi!  Have you used the "source" directory when installing in Dev Mode?

**Comment by scooterinab** [comment]
Do you mean downloading the source code for the extension? Or do you mean setting a path to the extension. I set the path to the extension and I repeatedly received the quoted error message. If I'm supposed to download the source code, I'm unsure how to do so, since it doesn't appear to have an extension file for Chrome to load.

**Comment by Cortys** [comment]
No. Apparently I was a bit too ambiguous. When install you should set the path to the folder called "source" inside the downloaded folder.

**Comment by scooterinab** [comment]
Thanks. I got it installed. Now it just doesn't work. There is no Extension button and nothing happens when I load a comic. There's no orange panel or Activate Scan button.

**Comment by Cortys** [comment]
The Orange Panel was replaced in version 2.0. The new UI is explained in the Readme: https://github.com/Cortys/comixology-backup/blob/master/README.md#how-to-use

**Comment by scooterinab** [comment]
But there is no different UI. There is no sign that this extension is working.

**Comment by Cortys** [comment]
That sound like a bug. It should look like this:
![screenshot 2016-05-10 13 42 14](https://cloud.githubusercontent.com/assets/1737630/15145327/2c78875c-16b5-11e6-8f50-984f843fa44c.png)

Which Chrome version and OS are you using?

**Comment by scooterinab** [comment]
The version of Chrome I'm running is Version 40.0.2214.111 m. I am using Windows 7, using all the most recent updates and any service packs.

I would also like to note that Chrome tries to disable the extension every time I open the browser. There's a dialog box that talks about the risks of running in Developer Mode and tries to disable the extension.

**Comment by Cortys** [comment]
Hi! While the extension should theoretically still work in Chrome v40, please try updating to v50. Unfortunately I don't have the time and resources to test the extension in every version of Chrome.

The warning about Dev Mode is not preventable and since the crx install method is disabled on every OS for some time now, there is no alternative so users have to live with it for now.

**Comment by scooterinab** [comment]
Thanks. It's working now. Chrome isn't my day to day browser, so I didn't realize I had an old version.

Thanks for your help.
