### ISSUE TITLE
Manifest is Missing or Invalid

### ISSUE THREAD

**Issue by NewAgeRipper** [Cortys/comixology-backup#90]
Tried adding the latest version to the Edge browser (which is exactly like Chrome) and no matter how I do it I get an error that the manifest is missing. Looking at your source code here I don't see any manifest. Is there a work around for this?

**Comment by TBK** [comment]
https://github.com/Cortys/comic-backup/blob/master/source/manifest.json

Edge being based on the Chromium source, does not mean it is 1:1 compatible - https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension

**Comment by NewAgeRipper** [comment]
> https://github.com/Cortys/comic-backup/blob/master/source/manifest.json
> 
> Edge being based on the Chromium source, does not mean it is 1:1 compatible - https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension

Dude, it's not even working with Chrome. please see if there is a solution. Not that I really need it anymore but it's still good to have in case. Chrome gives the same error when I try to sideload it. 
![image](https://user-images.githubusercontent.com/20009573/136634584-67129ef6-5280-40a7-8463-bf8bb6511e47.png)

**Comment by Cortys** [comment]
@NewAgeRipper Did you select the `source` directory to load the extension, as described in the [README](https://github.com/Cortys/comic-backup#installation)?

**Comment by NewAgeRipper** [comment]
> @NewAgeRipper Did you select the `source` directory to load the extension, as described in the [README](https://github.com/Cortys/comic-backup#installation)?

Yeah. I finally got it going. Realized that later. Used to I just had to select the download file and Chrome would see it. Thanks for the help.
