### ISSUE TITLE
add sponsor option (or buy me a coffe button)

### ISSUE THREAD

**Issue by manuartero** [Cortys/comixology-backup#91]
Hi there, 

thanks for this. Really. Works like a charm.

If you add [GitHub Sponsors](https://docs.github.com/en/sponsors) or a [Coffe](https://www.buymeacoffee.com/) button I'd ... well... send you a coffee basically

### ☕

**Comment by Cortys** [comment]
Hi, thanks for your support! While I currently don't plan to add a public donation button, I sent you a mail in case you want to support me nonetheless.
